# Project 1 - EDA 
#### Mason Reyher, Jamison Cleveland, Kade Aldrich, Mitch Froelich, Ryley Ourada

Initial setup:

In [1]:
%pip install --upgrade pip -q
%pip install pandas -q
%pip install numpy -q 
%pip install matplotlib -q

Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.


In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math

## Part 1

### In a well-written paragraph, answer the following questions about the data:

What was the data used for? </br>
**This data was used in a paper about multi-attribute decision making (Neural nets, trees, etc.) (8th Intl Workshop on Expert
   Systems and their Applications, Avignon, France. pages 59-78, 1988).** </br>
**It was also used for, "the evaluation
   of HINT (Hierarchy INduction Tool)" (B. Zupan, M. Bohanec, I. Bratko, J. Demsar: Machine learning by
   function decomposition. ICML-97, Nashville, TN. 1997).**

Who (or what organization) uploaded the data?</br>
**Marko Bohanec and Blaz Zupan, June 1997**


How many attributes and how many entities are represented in the data? </br>
**6 Attributes officially; for our purposes, 7, because of the 'class' attribute.** </br>
**The dataset has 1728 instances.**


How many numerical attributes? </br>
**2**


How many categorical attributes? </br>
**5**


Would you suggest that each categorical attribute be label-encoded or one-hot-
encoded? Why? </br>
**All categorical variables should be label encoded, not one-hot encoded. All variables are ranked via quality - for example, the price of a car 'buying' field is given a v-high, high, med, or low value. This is perfect for label-encoding. All other categorical variables assume this pattern as well.**

Are there missing values in the data? If so, what proportion of the data is missing
overall? What proportion of data is missing per attribute (you may use a plot or table to
summarize this information)?
</br>
**There is no missing data.**

Why is this data set interesting to you?
</br>
**ANSWER HERE**


Of the attributes used to describe this data, which do you think are the most
descriptive of the data and why (before doing any data analysis) ?
</br>
**the 'buying' and 'safety' attributes seem to be the most important. Before doing analysis, it would be probable to assume the more safe a car is, the more it would be worth. Most attributes are fairly important for a car (maintenace costs...), so the least important is likely the 'lug_boot' (trunk size) attribute, due to fields like cost and safety being much more important.**

## Part 2

Use Python to write the following functions, without using any functions with the same purpose
in sklearn, pandas, numpy, or any other library (though you may want to use these libraries to
check your answers):

A function that will compute the mean of a numerical, multidimensional data set
input as a 2-dimensional numpy array

In [3]:
# Input needs to be a 2d numpy array
def get_vector_mean(arr):
    return arr.sum(axis=0) / arr.size

A function that will compute the sample covariance between two attributes that are
input as one-dimensional numpy vectors

In [4]:
def get_cov(attr_1, attr_2):
    attr_1_mean = float(sum(attr_1)) / len(attr_1) 
    attr_2_mean = float(sum(attr_2)) / len(attr_2) 
    sum_of = 0
    for i in range(len(attr_1)):
        sum_of += (float(attr_1[i]) - attr_1_mean) * (float(attr_2[i]) - attr_2_mean)
    sum_of /= len(attr_1) - 1
    return sum_of

A function that will compute the correlation between two attributes that are input as
two numpy vectors.

In [5]:
def get_corr(attr_1, attr_2):
    attr_1_mean = float(sum(attr_1)) / len(attr_1) 
    attr_2_mean = float(sum(attr_2)) / len(attr_2)
    # find standard deviation
    attr_1_dev = 0
    attr_2_dev = 0
    for i in range(len(attr_1)):
        attr_1_dev += (attr_1[i] - attr_1_mean)**2
        attr_2_dev += (attr_2[i] - attr_2_mean)**2
    attr_1_dev = math.sqrt(attr_1_dev / len(attr_1))
    attr_2_dev = math.sqrt(attr_2_dev / len(attr_2))

    # standardize values
    for i in range(len(attr_1)):
        attr_1[i] = (attr_1[i] - attr_1_mean) / attr_1_dev
        attr_2[i] = (attr_2[i] - attr_2_mean) / attr_2_dev
   
    num = 0
    den_x = 0
    den_y = 0
    # calculate numerator and denominators
    for i in range(len(attr_1)):
        num += (float(attr_1[i]) - attr_1_mean) * (float(attr_2[i]) - attr_2_mean)
        den_x += (float(attr_1[i]) - attr_1_mean)**2
        den_y += (float(attr_2[i]) - attr_2_mean)**2
    # calculate full denominator
    den = den_x * den_y
    return num / den

A function that will normalize the attributes in a two-dimensional numpy array using
range normalization.

In [6]:

def get_range_norm(arr):
    max_ = arr.max()
    min_ = arr.min()
    return (arr - min_) / (max_ - min_)

A function that will normalize the attributes in a two-dimensional numpy array using
standard normalization.

In [7]:
# standard normalization is the z-score normalization
# https://en.wikipedia.org/wiki/Normalization_(statistics)#Examples
# https://en.wikipedia.org/wiki/Standard_score
def get_standard_norm(arr):
    mu = get_vector_mean(arr).T
    sigma = np.sqrt(np.apply_along_axis(lambda x: get_cov(x, x), 0, arr))
    return (arr - mu) / sigma

A function that will compute the covariance matrix of a data set.


In [8]:
def get_cov_matrix(df):
    return np.stack([np.array([get_cov(df[attr1], df[attr2]) for attr2 in df]) for attr1 in df])

A function that will label-encode a two-dimensional categorical data array that is
passed in as input.

In [9]:
def label_encode(attr):
    attr = list(attr)
    key_list = set(attr)
    keys = {}
    count = 0
    for key in key_list:
        keys[key] = count
        count+=1
    for i, val in enumerate(attr):
        attr[i] = keys[val]
    return np.array(attr)

## Part 3

## Questions to Answer:

In [17]:
df_orig = pd.read_csv('wines_red.csv', sep=";")
df_orig.columns = ['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide','density', 'pH', 'sulphates', 'alcohol', 'quality']

# label encode everything
df_orig['fixed acidity'] = label_encode(df_orig['fixed acidity'])
df_orig['volatile acidity'] = label_encode(df_orig['volatile acidity'])
df_orig['citric acid'] = label_encode(df_orig['citric acid'])
df_orig['residual sugar'] = label_encode(df_orig['residual sugar'])
df_orig['chlorides'] = label_encode(df_orig['chlorides'])
df_orig['free sulfur dioxide'] = label_encode(df_orig['free sulfur dioxide'])
df_orig['total sulfur dioxide'] = label_encode(df_orig['total sulfur dioxide'])
df_orig['density'] = label_encode(df_orig['density'])
df_orig['pH'] = label_encode(df_orig['pH'])
df_orig['sulphates'] = label_encode(df_orig['sulphates'])
df_orig['alcohol'] = label_encode(df_orig['alcohol'])
df_orig['quality'] = label_encode(df_orig['quality'])
df_orig.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0              9                72            0               1         96   
1              9                 0           72               2         97   
2             10                 1            1               0         35   
3              8                 2            0               0        108   
4              8                73            0               4         35   

   free sulfur dioxide  total sulfur dioxide  density  pH  sulphates  alcohol  \
0                   24                    61      365   3         50        4   
1                   14                    48       54   1         51        4   
2                   16                    54      324   2         52        4   
3                   10                    28      110   4          0        7   
4                   12                    34      110   4          0        7   

   quality  
0        2  
1        2  
2        3  
3        2  
4        2

What is the multivariate mean of the numerical data matrix (where categorical data
have been converted to numerical values)?

In [ ]:
df_copy = df_orig.copy()
mean = get_vector_mean(df_copy.to_numpy())
print(mean)

[0.21440979 0.21440979 0.21416163 0.14277442 0.14285714 0.14285714
 0.059641  ]


What is the covariance matrix of the numerical data matrix (where categorical data
have been converted to numerical values)?

In [ ]:
df_copy2 = df_orig.copy()
get_cov_matrix(df_copy2)

array([[ 1.25014409e+00, -1.30434695e-03,  1.30434695e-03,
         8.69564634e-04, -2.57293864e-19,  0.00000000e+00,
         1.99231616e-01],
       [-1.30434695e-03,  1.25014409e+00,  1.30434695e-03,
         8.69564634e-04, -2.57293864e-19,  0.00000000e+00,
         1.85906008e-01],
       [ 1.30434695e-03,  1.30434695e-03,  1.25014409e+00,
        -8.69564634e-04,  2.57293864e-19,  0.00000000e+00,
        -3.93243161e-02],
       [ 8.69564634e-04,  8.69564634e-04, -8.69564634e-04,
         6.66859456e-01,  0.00000000e+00,  0.00000000e+00,
        -2.05435987e-01],
       [-2.57293864e-19, -2.57293864e-19,  2.57293864e-19,
         0.00000000e+00,  6.67439166e-01,  0.00000000e+00,
        -2.25955968e-02],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  6.67439166e-01,
        -7.35805330e-02],
       [ 1.99231616e-01,  1.85906008e-01, -3.93243161e-02,
        -2.05435987e-01, -2.25955968e-02, -7.35805330e-02,
         5.5851210

Choose 5 pairs of attributes that you think could be related. Create scatter plots of
all 5 pairs and include these in your report, along with a description and analysis that
summarizes why these pairs of attributes might be related, and how the scatter plots do or
do not support this intuition.

Which range-normalized numerical attributes have the greatest sample covariance?

In [ ]:
d_matrix = df_orig.to_numpy()
get_range_norm(d_matrix)

array([[0.        , 0.        , 1.        , ..., 0.33333333, 0.66666667,
        0.        ],
       [0.        , 0.        , 1.        , ..., 0.33333333, 0.        ,
        0.        ],
       [0.        , 0.        , 1.        , ..., 0.66666667, 0.33333333,
        0.        ],
       ...,
       [0.66666667, 0.66666667, 0.        , ..., 0.        , 0.33333333,
        0.        ],
       [0.66666667, 0.66666667, 0.        , ..., 0.        , 0.66666667,
        1.        ],
       [0.66666667, 0.66666667, 0.        , ..., 0.        , 0.        ,
        0.66666667]])

What is their sample covariance? Create a scatter plot of these range-normalized attributes.

Which Z-score-normalized numerical attributes have the greatest correlation? What
is their correlation? Create a scatter plot of these Z-score-normalized attributes.

In [ ]:
d_matrix = df_orig.to_numpy()
get_standard_norm(d_matrix)

array([[-0.1917629 , -0.1917629 ,  2.49158598, ...,  1.04917363,
         2.27320953, -0.07980472],
       [-0.1917629 , -0.1917629 ,  2.49158598, ...,  1.04917363,
        -0.17486227, -0.07980472],
       [-0.1917629 , -0.1917629 ,  2.49158598, ...,  2.27320953,
         1.04917363, -0.07980472],
       ...,
       [ 1.59698839,  1.59698839, -0.19154095, ..., -0.17486227,
         1.04917363, -0.07980472],
       [ 1.59698839,  1.59698839, -0.19154095, ..., -0.17486227,
         2.27320953,  3.9344503 ],
       [ 1.59698839,  1.59698839, -0.19154095, ..., -0.17486227,
        -0.17486227,  2.59636529]])

Which Z-score-normalized numerical attributes have the smallest correlation? What
is their correlation? Create a scatter plot of these Z-score-normalized attributes.

How many pairs of features have correlation greater than or equal to 0.5?


In [ ]:
df_copy = df_orig.copy()
columns = df_copy.columns
column_check = {x : False for x in columns}
for column_1 in columns:
    for column_2 in columns:
        if column_1 == column_2 or not column_check[column_2]:
            continue
        # reset df because I don't understand references
        df_copy = df_orig.copy()
        print(f'Columns -> {column_1} - {column_2} -> correlation: {get_corr(df_copy[column_1], df_copy[column_2])}')
    column_check[column_1] = True

C:\Users\Owner\AppData\Local\Temp\ipykernel_56848\3397426948.py:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  attr_2[i] = (attr_2[i] - attr_2_mean) / attr_2_dev
C:\Users\Owner\AppData\Local\Temp\ipykernel_56848\3397426948.py:15: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  attr_1[i] = (attr_1[i] - attr_1_mean) / attr_1_dev


Columns -> maint - buying -> correlation: 0.0001232334898328454
Columns -> doors - buying -> correlation: 0.00012340272003412485
Columns -> doors - maint -> correlation: 0.0001234027200341299
Columns -> persons - buying -> correlation: 0.00013367936957312462
Columns -> persons - maint -> correlation: 0.0001336793695731284
Columns -> persons - doors -> correlation: 0.00013356911005642304
Columns -> lug_boot - buying -> correlation: 0.00013359457119492248
Columns -> lug_boot - maint -> correlation: 0.00013359457119492603
Columns -> lug_boot - doors -> correlation: 0.0001336540893814914
Columns -> lug_boot - persons -> correlation: 0.0001447596746178213
Columns -> safety - buying -> correlation: 0.00013359457119492248
Columns -> safety - maint -> correlation: 0.00013359457119492603
Columns -> safety - doors -> correlation: 0.0001336540893814914
Columns -> safety - persons -> correlation: 0.0001447596746178213
Columns -> safety - lug_boot -> correlation: 0.00014475969889982243
Columns -> c

**No pairs of features have a correlation of >= 0.5.**

How many pairs of features have negative sample covariance?


What is the total variance of the data?


In [ ]:
def get_total_var(arr) :
    mean = get_vector_mean(arr)
    for i in arr:
        arr[i] = arr[i] - mean
    sum_sqdiff = arr.sum()
    var = sum_sqdiff / arr.size
    return var
df_copy3 = df_orig.copy()
get_total_var(df_copy3.to_numpy())

1.0395557267140796


1.1285466126230457

What is the total variance of the data, restricted to the five features that have the
greatest sample variance?