# Project 1 - EDA 
#### Mason Reyher, Jamison Cleveland, Kade Aldrich, Mitch Froelich, Ryley Ourada

Initial setup:

In [ ]:
%pip install --upgrade pip -q
%pip install pandas -q
%pip install numpy -q 
%pip install matplotlib -q

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math

## Part 1

### In a well-written paragraph, answer the following questions about the data:

What was the data used for? </br>
**This data was used in a paper about multi-attribute decision making (Neural nets, trees, etc.) (8th Intl Workshop on Expert
   Systems and their Applications, Avignon, France. pages 59-78, 1988).** </br>
**It was also used for, "the evaluation
   of HINT (Hierarchy INduction Tool)" (B. Zupan, M. Bohanec, I. Bratko, J. Demsar: Machine learning by
   function decomposition. ICML-97, Nashville, TN. 1997).**

Who (or what organization) uploaded the data?</br>
**Marko Bohanec and Blaz Zupan, June 1997**


How many attributes and how many entities are represented in the data? </br>
**6 Attributes officially; for our purposes, 7, because of the 'class' attribute.** </br>
**The dataset has 1728 instances.**


How many numerical attributes? </br>
**2**


How many categorical attributes? </br>
**5**


Would you suggest that each categorical attribute be label-encoded or one-hot-
encoded? Why? </br>
**All categorical variables should be label encoded, not one-hot encoded. All variables are ranked via quality - for example, the price of a car 'buying' field is given a v-high, high, med, or low value. This is perfect for label-encoding. All other categorical variables assume this pattern as well.**

Are there missing values in the data? If so, what proportion of the data is missing
overall? What proportion of data is missing per attribute (you may use a plot or table to
summarize this information)?
</br>
**There is no missing data.**

Why is this data set interesting to you?
</br>
**ANSWER HERE**


Of the attributes used to describe this data, which do you think are the most
descriptive of the data and why (before doing any data analysis) ?
</br>
**the 'buying' and 'safety' attributes seem to be the most important. Before doing analysis, it would be probable to assume the more safe a car is, the more it would be worth. Most attributes are fairly important for a car (maintenace costs...), so the least important is likely the 'lug_boot' (trunk size) attribute, due to fields like cost and safety being much more important.**

## Part 2

Use Python to write the following functions, without using any functions with the same purpose
in sklearn, pandas, numpy, or any other library (though you may want to use these libraries to
check your answers):

A function that will compute the mean of a numerical, multidimensional data set
input as a 2-dimensional numpy array

In [112]:
# Input needs to be a 2d numpy array
def get_vector_mean(arr):
    return arr.sum(axis=0) / arr.shape[0]

array([3. , 4.5])

A function that will compute the sample covariance between two attributes that are
input as one-dimensional numpy vectors

In [118]:
def get_cov(attr_1, attr_2):
    attr_1_mean = float(sum(attr_1)) / len(attr_1) 
    attr_2_mean = float(sum(attr_2)) / len(attr_2) 
    sum_of = 0
    for i in range(len(attr_1)):
        sum_of += (float(attr_1[i]) - attr_1_mean) * (float(attr_2[i]) - attr_2_mean)
    sum_of /= len(attr_1) - 1
    return sum_of

def get_var(arr):
    return np.apply_along_axis(lambda x: get_cov(x, x), 0, arr)

array([0.09670396, 0.16844559])

A function that will compute the correlation between two attributes that are input as
two numpy vectors.

In [9]:
def get_corr(attr_1, attr_2):
    attr_1_mean = float(sum(attr_1)) / len(attr_1) 
    attr_2_mean = float(sum(attr_2)) / len(attr_2)
    # find standard deviation
    attr_1_dev = 0
    attr_2_dev = 0
    for i in range(len(attr_1)):
        attr_1_dev += (attr_1[i] - attr_1_mean)**2
        attr_2_dev += (attr_2[i] - attr_2_mean)**2
    attr_1_dev = math.sqrt(attr_1_dev / len(attr_1))
    attr_2_dev = math.sqrt(attr_2_dev / len(attr_2))

    # standardize values
    for i in range(len(attr_1)):
        attr_1[i] = (attr_1[i] - attr_1_mean) / attr_1_dev
        attr_2[i] = (attr_2[i] - attr_2_mean) / attr_2_dev
   
    num = 0
    den_x = 0
    den_y = 0
    # calculate numerator and denominators
    for i in range(len(attr_1)):
        num += (float(attr_1[i]) - attr_1_mean) * (float(attr_2[i]) - attr_2_mean)
        den_x += (float(attr_1[i]) - attr_1_mean)**2
        den_y += (float(attr_2[i]) - attr_2_mean)**2
    # calculate full denominator
    den = den_x * den_y
    return num / den

A function that will normalize the attributes in a two-dimensional numpy array using
range normalization.

In [92]:
def get_range_norm(arr):
    max_ = arr.max(0)
    min_ = arr.min(0)
    return (arr - min_) / (max_ - min_)

A function that will normalize the attributes in a two-dimensional numpy array using
standard normalization.

In [106]:
# standard normalization is the z-score normalization
# https://en.wikipedia.org/wiki/Normalization_(statistics)#Examples
# https://en.wikipedia.org/wiki/Standard_score
def get_standard_norm(arr):
    mu = get_vector_mean(arr)
    sigma = np.sqrt(get_var(arr))
    return (arr - mu) / sigma

A function that will compute the covariance matrix of a data set.


In [18]:
def get_cov_matrix(df):
    return np.stack([np.array([get_cov(df[attr1], df[attr2]) for attr2 in df]) for attr1 in df])

A function that will label-encode a two-dimensional categorical data array that is
passed in as input.

In [13]:
def label_encode(attr):
    attr = list(attr)
    key_list = set(attr)
    keys = {}
    count = 0
    for key in key_list:
        keys[key] = count
        count+=1
    for i, val in enumerate(attr):
        attr[i] = keys[val]
    return np.array(attr)

## Part 3

## Questions to Answer:

In [14]:
df_orig = pd.read_csv('car.data')
df_orig.columns = ['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'class']

# label encode everything
df_orig['buying'] = label_encode(df_orig['buying'])
df_orig['maint'] = label_encode(df_orig['maint'])
df_orig['doors'] = label_encode(df_orig['doors'])
df_orig['persons'] = label_encode(df_orig['persons'])
df_orig['lug_boot'] = label_encode(df_orig['lug_boot'])
df_orig['safety'] = label_encode(df_orig['safety'])
df_orig['class'] = label_encode(df_orig['class'])
df_orig.head()

buying  maint  doors  persons  lug_boot  safety  class
0       1      1      2        1         1       1      1
1       1      1      2        1         1       2      1
2       1      1      2        1         2       0      1
3       1      1      2        1         2       1      1
4       1      1      2        1         2       2      1

What is the multivariate mean of the numerical data matrix (where categorical data
have been converted to numerical values)?

In [69]:
df_copy = df_orig.copy()
get_vector_mean(df_copy.to_numpy())

[1.50028952 1.50028952 1.49971048 1.         1.         1.00057904
 1.25767226]


What is the covariance matrix of the numerical data matrix (where categorical data
have been converted to numerical values)?

In [19]:
df_copy2 = df_orig.copy()
get_cov_matrix(df_copy2)

array([[ 1.25130351e+00, -1.44927439e-04,  1.44927439e-04,
        -7.71881593e-19,  2.57293864e-19, -2.89854878e-04,
         9.48503121e-03],
       [-1.44927439e-04,  1.25130351e+00,  1.44927439e-04,
        -3.85940797e-18,  2.57293864e-19, -2.89854878e-04,
         4.94618562e-02],
       [ 1.44927439e-04,  1.44927439e-04,  1.25130351e+00,
        -2.57293864e-19, -2.57293864e-19,  2.89854878e-04,
        -7.16753411e-03],
       [-7.71881593e-19, -3.85940797e-18, -2.57293864e-19,
         6.67439166e-01,  0.00000000e+00,  0.00000000e+00,
         5.79374276e-04],
       [ 2.57293864e-19,  2.57293864e-19, -2.57293864e-19,
         0.00000000e+00,  6.67439166e-01,  0.00000000e+00,
        -2.25955968e-02],
       [-2.89854878e-04, -2.89854878e-04,  2.89854878e-04,
         0.00000000e+00,  0.00000000e+00,  6.66859456e-01,
         1.75980491e-01],
       [ 9.48503121e-03,  4.94618562e-02, -7.16753411e-03,
         5.79374276e-04, -2.25955968e-02,  1.75980491e-01,
         3.4666039

Choose 5 pairs of attributes that you think could be related. Create scatter plots of
all 5 pairs and include these in your report, along with a description and analysis that
summarizes why these pairs of attributes might be related, and how the scatter plots do or
do not support this intuition.

Which range-normalized numerical attributes have the greatest sample covariance?

In [145]:
from math import inf

df1 = pd.DataFrame(get_range_norm(df_orig.to_numpy()), columns=df_orig.columns)
covar_matrix = get_cov_matrix(df1)
# set diagonals to -inf so we only get max of off-diagonals
## a bit hacky
covar_matrix += np.diag(np.full(covar_matrix.shape[0], -inf))

# take the flat index to the array,
# get the indicies for each attribute,
# then return the labels for each attribute
flat_idx = covar_matrix.argmax()
idx = np.unravel_index(flat_idx, df1.shape)
[df1.columns[i] for i in idx]

['safety', 'class']

What is their sample covariance? Create a scatter plot of these range-normalized attributes.

Which Z-score-normalized numerical attributes have the greatest correlation? What
is their correlation? Create a scatter plot of these Z-score-normalized attributes.

In [121]:
d_matrix = df_orig.to_numpy()
get_standard_norm(d_matrix)

array([[-329.99939085, -329.99939085, -328.97772091, ..., -300.7631073 ,
        -301.06874584, -525.30041831],
       [-329.99939085, -329.99939085, -328.97772091, ..., -300.7631073 ,
        -299.84417801, -525.30041831],
       [-329.99939085, -329.99939085, -328.97772091, ..., -299.5390714 ,
        -302.29331366, -525.30041831],
       ...,
       [-330.89335205, -330.89335205, -328.08375972, ..., -301.9871432 ,
        -302.29331366, -525.30041831],
       [-330.89335205, -330.89335205, -328.08375972, ..., -301.9871432 ,
        -301.06874584, -526.99884922],
       [-330.89335205, -330.89335205, -328.08375972, ..., -301.9871432 ,
        -299.84417801, -521.90355648]])

Which Z-score-normalized numerical attributes have the smallest correlation? What
is their correlation? Create a scatter plot of these Z-score-normalized attributes.

How many pairs of features have correlation greater than or equal to 0.5?


In [ ]:
df_copy = df_orig.copy()
columns = df_copy.columns
column_check = {x : False for x in columns}
for column_1 in columns:
    for column_2 in columns:
        if column_1 == column_2 or not column_check[column_2]:
            continue
        # reset df because I don't understand references
        df_copy = df_orig.copy()
        print(f'Columns -> {column_1} - {column_2} -> correlation: {get_corr(df_copy[column_1], df_copy[column_2])}')
    column_check[column_1] = True

**No pairs of features have a correlation of >= 0.5.**

How many pairs of features have negative sample covariance?


What is the total variance of the data?


What is the total variance of the data, restricted to the five features that have the
greatest sample variance?